name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_focal:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Run Workflow
        run: |
            make github-workflow
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: stubby
          path: |
            stubby.efi
            sbat.csv
      - name: Upload Test Results
        if: '!cancelled()'
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: test-data
          path: test-data.tar

  build_jammy:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Run Workflow
        run: |
            make github-workflow
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: stubby
          path: |
            stubby.efi
            sbat.csv
      - name: Upload Test Results
        if: '!cancelled()'
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: test-data
          path: test-data.tar
